### ISSUE TITLE
Complex differentiation

### ISSUE THREAD

**Issue by lcw** [jverzani/SymPy.jl#27]
Thanks for the cool package.  When trying to differentiate a complex function I got a weird result.  For example
```
julia> using SymPy
Warning: imported binding for transpose overwritten in module __anon__

julia> x=sym"x"
x

julia> diff(exp(im*x), x)
        true*I⋅x
true*I⋅ℯ
```
Why is a true in the resulting equation?  Is there something I am doing wrong?

Thanks for you help,
Lucas

**Comment by jverzani** [comment]
Hmm, wasn't expecting that. Multiplying by `true` is just like multiplying by 1, but still...  I likely can workaround this, but for now your best bet is to use `IM`, and not `im`. The `IM` variable is aliased to sympy's imaginary unit, not julia's. Unfortunately, I forgot to export IM. So you'll need to update to master or prefix as follows:

```
julia> diff(exp(SymPy.IM*x), x)
   ⅈ⋅x
ⅈ⋅ℯ   
```

I'll leave this issue open as a reminder to see if I can do something so that using `im` works. I just checked in some changes that make working with math constants more julian.

**Comment by lcw** [comment]
Thanks for checking it out.  That is an easy workaround for now.

**Comment by jverzani** [comment]
I just pushed a change so that it works with the call you had (sans `IM`). I aim to tag a new version pretty soon.

**Comment by jverzani** [comment]
Oh, and thanks for taking the time to report the issue.

**Comment by lcw** [comment]
Thanks!
