### ISSUE TITLE
Python functions which accept lists does not do so in Julia

### ISSUE THREAD

**Issue by baggepinnen** [jverzani/SymPy.jl#59]
Consider the function `cse`, which in python accepts lists with expressions. If you send in an array in Julia, you get an error. I worked around it by redefining line 186 in SymPy.jl
from 
`($meth)(ex::Sym, args...; kwargs...) = sympy_meth(symbol($meth_name), ex, args...; kwargs...)`
to
`($meth)(ex, args...; kwargs...) = sympy_meth(symbol($meth_name), ex, args...; kwargs...)`

**Comment by jverzani** [comment]
Thanks for pointing this out! I see the problem, but this isn't such a good fix, as there can be conflicts with Base functions. (such as `collect`.) Seems better to add a vectorized from for the method. Rather than your suggestion, try adding this line just after:
```
 ($meth){T<:SymbolicObject}(ex::Vector{T}, args...; kwargs...) = sympy_meth(symbol($meth_name), map(project,ex), args...; kwargs...)
```

and let me know if that helps solve this issue. The tests still pass, but I need to add tests for this behavior. If that works, you can put together a PR if you want, or I can push my changes.

**Comment by baggepinnen** [comment]
I tried your method which works well for julia arrays of dim 1, so for an array of dim 2 (matrx) i had to vectorize the input and then reshape the output, like this
```julia
    change,res = cse(AA[:])
    reshape(res,size(AA))
```

**Comment by jverzani** [comment]
That's not good. We can change Vector{T} to Array{T] in the definition and it should work.

**Comment by baggepinnen** [comment]
Unfortunately, this method (with Array{T}) produces an error

```julia
julia> change,res = cse(AA);
ERROR: PyError (:PyObject_Call) <type 'exceptions.AttributeError'>
AttributeError("'list' object has no attribute 'atoms'",)
  File "/home/fredrikb/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/sympy/simplify/cse_main.py", line 441, in cse
    for expr in reduced_exprs])

 [inlined code] from /home/fredrikb/.julia/v0.4/PyCall/src/exception.jl:81
 in pycall at /home/fredrikb/.julia/v0.4/PyCall/src/PyCall.jl:361
 in fn at /home/fredrikb/.julia/v0.4/PyCall/src/conversions.jl:194
 in call_sympy_fun at /home/fredrikb/.julia/v0.4/SymPy/src/SymPy.jl:263
 in sympy_meth at /home/fredrikb/.julia/v0.4/SymPy/src/SymPy.jl:269
 in cse at /home/fredrikb/.julia/v0.4/SymPy/src/SymPy.jl:188
```

**Comment by jverzani** [comment]
Can you show me what defines AA? I'd like to think there is a convenient
workaround to this and that will help me debug it. Thanks

On Tue, Jan 26, 2016 at 9:11 AM, baggepinnen <notifications@github.com>
wrote:

> Unfortunately, this method (with Array{T}) produces an error
>
> julia> change,res = cse(AA);
> ERROR: PyError (:PyObject_Call) <type 'exceptions.AttributeError'>AttributeError("'list' object has no attribute 'atoms'",)
>   File "/home/fredrikb/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/sympy/simplify/cse_main.py", line 441, in cse
>     for expr in reduced_exprs])
>
>  [inlined code] from /home/fredrikb/.julia/v0.4/PyCall/src/exception.jl:81
>  in pycall at /home/fredrikb/.julia/v0.4/PyCall/src/PyCall.jl:361
>  in fn at /home/fredrikb/.julia/v0.4/PyCall/src/conversions.jl:194
>  in call_sympy_fun at /home/fredrikb/.julia/v0.4/SymPy/src/SymPy.jl:263
>  in sympy_meth at /home/fredrikb/.julia/v0.4/SymPy/src/SymPy.jl:269
>  in cse at /home/fredrikb/.julia/v0.4/SymPy/src/SymPy.jl:188
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/SymPy.jl/issues/59#issuecomment-175033406>.
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by baggepinnen** [comment]
The matrix `AA` is the result of the following code, if it helps I can try to setup a small example which reproduces the error. 
```julia
AA = zeros(Sym,n_joints, 4n_joints);
    for i = 1:n_joints
        for j = 1:size(AA,2)
            AA[i,j] = coeff(eq[i],w[j]);
        end
        print(i)
    end
julia> typeof(AA)
Array{SymPy.Sym,2}
```

**Comment by jverzani** [comment]
Thanks, this is an issue with how SymPy.jl uses Julia arrays to store
symbolic objects, rather than SymPy arrays. I have  some other ways of
doing this, but none seem better than manually doing linear indexing and
reshaping:

1)

```
cse(convert(SymMatrix, AA))
```

This returns a symbolic matrix object which, if desired, can be converted
to an Array{Sym} object. This step may not be necessary, but is for many
subsequent manipulations.

2) I could put the linear indexing/reshaping code into the method, but
while that may be the right thing for cse, it may not be for other
functions.


For now, I think your workaround is best. Thoughts?

On Tue, Jan 26, 2016 at 9:16 AM, baggepinnen <notifications@github.com>
wrote:

> The matrix AA is the result of the following code, if it helps I can try
> to setup a small example which reproduces the error.
>
> AA = zeros(Sym,n_joints, 4n_joints);
>     for i = 1:n_joints
>         for j = 1:size(AA,2)
>             AA[i,j] = coeff(eq[i],w[j]);
>         end
>         print(i)
>     end
> julia> typeof(AA)
> Array{SymPy.Sym,2}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/SymPy.jl/issues/59#issuecomment-175035346>.
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by jverzani** [comment]
Okay, I decided to special case `cse` as the more general solution was leaving arrays of type Any. If you find other instances where a list is needed, could you let me know? I'll implement the general pattern in that case. Thanks!

**Comment by baggepinnen** [comment]
Thanks, your effort is much appreciated! I will let you know, should I find any more cases!
