### ISSUE TITLE
how to works eval(m, x)?

### ISSUE THREAD

**Issue by jmarcellopereira** [jverzani/SymPy.jl#78]
?SymPy.eval

Out[1]:
No documentation found.
SymPy.eval is a generic Function.

**Comment by jverzani** [comment]
The `eval` function is part of base `Julia`. SymPy has `evalf` which works within Julia as it does under Python (`N` is different under Julia). I think what you are seeing is `PyCall.eval` as SymPy uses PyCall.

What are you trying to do though? Maybe I can help.

**Comment by jmarcellopereira** [comment]
hello Verzani
actually i want to use a command that calculates this way:
         command(symbolic_fun(x), x value)
no map;). Searching, I found the eval(m, x) but have not found documentation.

**Comment by jverzani** [comment]
You want to pass a function to `command`, as in `command(f, x)` or call the symbolic function on the variable x, as in `f(x)`? As well, is the symbolic function an instance of SymFunction or just an expression of different variables? Maybe a code snippet can help clarify.

**Comment by jmarcellopereira** [comment]
Hi jverzani ,this is the idea:
using SymPy
@syms x
fsym = x.^ 2
w = 1:3
command(fsym(w), w) -  does not work

this type of code is possible with the generic function:
w = 0: 3
fgen (x) = x. ^ 2
eval(fgen(w))

**Comment by jverzani** [comment]
Oh, that is interesting, but unfortunately I'm not sure how to make this work.

The definition `fsym = x.^2` dispatches to the definition for number .^ number and calls x^2 at the time of defintion. Whereas, when you evaluate `fsym` you need the method for .^ in `arraymath.jl`. I'm not sure I can do much here, but here are some suggestions:

* use `map` or `broadcast`. (I know you don't want to but `map(fsym, w)` will work.)
* use a function: `fsym(x) = x.^2` then pass in symbolic values
* wait until 0.5 in which case the `.(` notation will broadcast, so that `fsym.(w)` will work as you want. And in fact, `fsym=x^2; fsym.(w)` will work.

SymPy currently works under a recent development version (I just checked 17-days old).

(One last thing, you should backquote the use of the "at" symbol, I think the `syms` GithHub user is likely involved in the conversation now.)

**Comment by jmarcellopereira** [comment]
@jverzani 
okay fine. but just out of curiosity, how to use "eval(m, x)"?

**Comment by jverzani** [comment]
As far as I know, the `m` there is a module and `x` and expression to
evaluate within that module. (Thisis the eval in Base Julia.) I don't think
there is a version where `m` is a symbolic expression and x a variable.
There is `subs` and the convenient `call` method for that.

On Fri, Jul 8, 2016 at 4:10 PM, joão marcello <notifications@github.com>
wrote:

> @jverzani <https://github.com/jverzani>
> okay fine. but just out of curiosity, how to use "eval(m, x)"?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jverzani/SymPy.jl/issues/78#issuecomment-231460314>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAZvTGEiTWTiF0uo5NkEcWH2cItw5OZxks5qTq7SgaJpZM4JIIoF>
> .
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by jmarcellopereira** [comment]
@jverzani 
okay fine ;)
